In [7]:
import cv2
from PIL import Image
import numpy as np
import matplotlib.pylab as pylab
img=np.zeros((8,8),dtype=np.uint8)
print(img)
pylab.gray()
lena=cv2.imread('./Lenna.png')#path指图片相关路径
cv2.namedWindow("winname")
cv2.imshow("winname", lena) 
cv2.waitKey(0)
cv2.destroyAllWindows()

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


<Figure size 432x288 with 0 Axes>

In [2]:
import numpy as np
import cv2
from PIL import Image
import numpy as np
import matplotlib.pylab as pyla
blue=np.zeros((300,300,3),dtype=np.uint8)
blue[:,:,0]=255
print("blue=",blue)
blue=cv2.cvtColor(blue,cv2.COLOR_BGR2RGB)

cv2.namedWindow("winname")
cv2.imshow("winname", blue) 
cv2.waitKey(0)
cv2.destroyAllWindows()


blue= [[[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 ...

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[255   0   0]
  [255   0   0]
  [255   0   0]
  ...
  [255   0   0]
  [255   0   0]
  [255   0   0]]]
